version: '2'
services:
    truckplanner-app:
        image: truckplanner
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://truckplanner-postgresql:5432/truckplanner
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    truckplanner-postgresql:
        extends:
            file: postgresql.yml
            service: truckplanner-postgresql
